remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
title: "Oodles Blockchain Blog"
description: "Latest insights, innovations, and trends in blockchain technology."
author:
  name: "Oodles Blockchain"
  avatar: "/assets/images/company-logo.png"
logo: "/assets/images/company-logo.png"
theme_skin: "default"  # Change to "dark" for a dark theme
